Added support for SRT and RIST streaming protocols
linuxserver/docker-ffmpeg pull request #82
Opened 2024-08-14 04:14 UTC by d-prieur

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [ ] I have read the [contributing](https://github.com/linuxserver/docker-ffmpeg/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Added support for the SRT protocol by pulling the latest tag from Haivision's GitHub repository and building it with shared libraries enabled using CMake & Make.
Added support for the RIST protocol by pulling the latest tag from VideoLAN's GitLab repository and building it with shared libraries enabled using Meson & Ninja.

I did not include the changes in the Dockerfile.aarch64 as I currently do not have any way of testing this architecture but to extend the functionality to it should probably be just a question of copying and pasting the code into the file.

## Benefits of this PR and context:

This extends the capabilities of the FFMPEG tool provided in this container image by allowing the user to stream in and out using the added modern video streaming protocols.

## How Has This Been Tested?

1. Checked that no build error occurred when creating the image from the Dockerfile
2. Checked that the protocols were available for both input and output with the "-protocols" command line option
3. Did a quick streaming test to show that FFMPEG in the container is able to stream a video using the protocols to FFPLAY on the host computer

## Source / References:

https://github.com/Haivision/srt
https://code.videolan.org/rist/librist

2024-08-14 04:18 UTC, aptalca commented on Dockerfile
> +  SRT=1.5.3 \
Should come before svtav1

2024-08-14 04:20 UTC, aptalca commented on Dockerfile
> +    --enable-librist \
Please list in alphabetical order

2024-08-14 04:21 UTC, aptalca requested changes
Thanks for the PR.
Please add them to the aarch64 dockerfile as well

2024-08-16 23:32 UTC, d-prieur commented
I have tried addressing all the requested changes. Please let me know if my updates are not what was expected or if there is anything I need to do to keep this moving along. Thank you.

2024-08-17 17:25 UTC, aptalca approved these changes

2024-08-17 17:26 UTC, merged